"""
terraform_export.py
Exports existing Azure resources to Terraform HCL using aztfexport.

Design (simplified):
  - ONE main.tf per resource group (no splitting by kind)
  - The resource group itself is included as an azurerm_resource_group block
    so a from-scratch rebuild recreates the RG too
  - providers.tf with azurerm provider + Azure Storage remote backend
  - DEPLOY.md with step-by-step deployment instructions

Folder layout under the output root:
    <subscription-name>/
        <resource-group-1>/
            main.tf
            providers.tf
            DEPLOY.md
        <resource-group-2>/
            main.tf
            providers.tf
            DEPLOY.md
        ...

When the whole subscription is selected, every resource group gets its own
folder. When a single RG is selected, only that folder is created.

IMPORTANT: aztfexport exports resource *configuration*, not data. Re-applying
into a fresh subscription rebuilds the infrastructure shell; VM disk contents
and storage data are NOT restored by Terraform (use Azure Backup for data).
"""
import os
import re
import shutil
import subprocess
import tempfile

from inventory import list_resource_groups
from azure_clients import resource_client


def aztfexport_available():
    """Return (ok, version_or_error)."""
    exe = shutil.which("aztfexport")
    if not exe:
        return False, "aztfexport not found on PATH"
    try:
        out = subprocess.run([exe, "--version"], capture_output=True, text=True, timeout=20)
        return True, (out.stdout or out.stderr).strip()
    except Exception as e:
        return False, str(e)


def _safe_name(name):
    return re.sub(r"[^A-Za-z0-9._-]", "_", name)


def _rg_location(subscription_id, rg_name):
    """Look up the RG's location so we can emit a correct resource_group block."""
    try:
        rc = resource_client(subscription_id)
        rg = rc.resource_groups.get(rg_name)
        return rg.location
    except Exception:
        return "eastus"  # safe fallback; user can edit


def _ensure_rg_block(main_tf_text, rg_name, location):
    """
    Ensure an azurerm_resource_group block exists in the HCL. If aztfexport
    already emitted one for this RG, leave it. Otherwise prepend one.
    """
    if re.search(r'resource\s+"azurerm_resource_group"', main_tf_text):
        return main_tf_text  # already present

    block = f'''# Resource group (added by Azure Governance Bot so a from-scratch
# rebuild recreates the RG itself).
resource "azurerm_resource_group" "this" {{
  name     = "{rg_name}"
  location = "{location}"
}}

'''
    return block + main_tf_text


def export_resource_group(subscription_id, subscription_name, rg_name, out_root):
    """Export one RG to <out_root>/<sub>/<rg>/main.tf (+ providers + DEPLOY.md)."""
    exe = shutil.which("aztfexport")
    if not exe:
        raise RuntimeError("aztfexport not found on PATH. See README for install steps.")

    sub_dir = os.path.join(out_root, _safe_name(subscription_name))
    rg_dir = os.path.join(sub_dir, _safe_name(rg_name))
    os.makedirs(rg_dir, exist_ok=True)

    # Pin the subscription for CLI context + credential fallback.
    az = shutil.which("az") or shutil.which("az.cmd")
    if az:
        try:
            subprocess.run([az, "account", "set", "--subscription", subscription_id],
                           capture_output=True, text=True, timeout=60)
        except Exception:
            pass

    env = dict(os.environ)
    env["ARM_SUBSCRIPTION_ID"] = subscription_id
    env["AZURE_SUBSCRIPTION_ID"] = subscription_id

    with tempfile.TemporaryDirectory() as tmp:
        cmd = [exe, "resource-group", "--non-interactive", "--hcl-only",
               "--name-pattern", "res_",
               "--continue",
               "--subscription-id", subscription_id,
               "--output-dir", tmp, rg_name]
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=1800, env=env)
        combined = (proc.stdout or "") + "\n" + (proc.stderr or "")
        lc = combined.lower()
        empty_rg = ("no resource" in lc or "no resources" in lc or "nothing to" in lc)
        if proc.returncode != 0 and not empty_rg:
            raise RuntimeError(
                f"aztfexport exited {proc.returncode} for RG '{rg_name}':\n"
                f"{combined.strip()}")

        main_tf_src = os.path.join(tmp, "main.tf")
        if os.path.isfile(main_tf_src):
            with open(main_tf_src, "r", encoding="utf-8") as f:
                hcl = f.read()
        else:
            hcl = "# (No resources found in this resource group.)\n"

        resource_count = len(re.findall(r'^\s*resource\s+"', hcl, re.MULTILINE))

    location = _rg_location(subscription_id, rg_name)
    hcl = _ensure_rg_block(hcl, rg_name, location)

    header = (f"# main.tf — generated by Azure Governance Bot\n"
              f"# Resource group: {rg_name}\n"
              f"# Subscription:   {subscription_name} ({subscription_id})\n\n")
    with open(os.path.join(rg_dir, "main.tf"), "w", encoding="utf-8") as f:
        f.write(header + hcl)

    _write_providers(rg_dir, subscription_id)
    _write_deploy_md(rg_dir, subscription_name, subscription_id, rg_name, resource_count)

    return {"resource_group": rg_name, "path": rg_dir,
            "resource_total": resource_count, "empty": resource_count == 0}


def _write_providers(out_dir, subscription_id):
    content = f'''# providers.tf — generated by Azure Governance Bot
terraform {{
  required_version = ">= 1.5.0"

  required_providers {{
    azurerm = {{
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }}
  }}

  # --------------------------------------------------------------------------
  # Remote state backend (Azure Storage).
  # Fill these in (or pass via -backend-config) before `terraform init`.
  # Keep this storage OUTSIDE the subscription you are restoring, so the state
  # survives if that subscription is deleted.
  # --------------------------------------------------------------------------
  backend "azurerm" {{
    resource_group_name  = "REPLACE_tfstate_rg"
    storage_account_name = "REPLACE_tfstate_storage"
    container_name       = "tfstate"
    key                  = "{subscription_id}.tfstate"
  }}
}}

provider "azurerm" {{
  features {{}}
  subscription_id = "{subscription_id}"
}}
'''
    with open(os.path.join(out_dir, "providers.tf"), "w", encoding="utf-8") as f:
        f.write(content)


def _write_deploy_md(out_dir, subscription_name, subscription_id, rg_name, resource_count):
    content = f'''# Deployment Instructions — {rg_name}

Generated by **Azure Governance Bot** using `aztfexport`.

- **Subscription:** {subscription_name} (`{subscription_id}`)
- **Resource group:** {rg_name}
- **Resources captured:** {resource_count}

This folder contains:
- `main.tf` — all resources in this resource group, plus the resource group itself
- `providers.tf` — azurerm provider + Azure Storage remote backend

---

## What this restores (and what it does NOT)
`terraform apply` rebuilds the **infrastructure**: the resource group, VNets,
subnets, NSGs, VM definitions, storage accounts, etc.

It does **NOT** restore data:
- VM OS/data **disk contents** (come back as fresh disks from the image)
- **Storage data** (blobs, files, tables, queues come back empty)
- **Database contents**

For data, use **Azure Backup / Recovery Services**. Treat this as
infrastructure rebuild, not full disaster recovery.

---

## Prerequisites
1. Terraform >= 1.5 installed (`terraform -version`).
2. Logged in to Azure: `az login` (and the right tenant if needed).
3. An existing Azure Storage account + container for remote state, in a
   DIFFERENT subscription from the one being restored. Update the
   `backend "azurerm"` block in `providers.tf` with its details.
4. Permission to create resources in the target subscription.

---

## Deploy locally
```bash
cd "{_safe_name(subscription_name)}/{_safe_name(rg_name)}"

# 1. Initialize (connects to remote state)
terraform init

# 2. Preview what will be created
terraform plan

# 3. Create the infrastructure
terraform apply
```

Review the `terraform plan` output before applying. aztfexport output is a
faithful but verbose starting point; some attributes the Azure API does not
return (e.g. secrets) may need manual edits before a clean apply.

---

## Deploy from Azure DevOps (pipeline)
Example `azure-pipelines.yml`:
```yaml
trigger:
  branches:
    include: [ main ]

pool:
  vmImage: ubuntu-latest

variables:
  workdir: '{_safe_name(subscription_name)}/{_safe_name(rg_name)}'

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: latest

  - task: TerraformTaskV4@4
    displayName: Init
    inputs:
      provider: azurerm
      command: init
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(workdir)'
      backendServiceArm: '<azure-service-connection>'
      backendAzureRmResourceGroupName: '<tfstate-rg>'
      backendAzureRmStorageAccountName: '<tfstate-storage>'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: '{subscription_id}.tfstate'

  - task: TerraformTaskV4@4
    displayName: Plan
    inputs:
      provider: azurerm
      command: plan
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(workdir)'
      environmentServiceNameAzureRM: '<azure-service-connection>'

  - task: TerraformTaskV4@4
    displayName: Apply
    inputs:
      provider: azurerm
      command: apply
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(workdir)'
      environmentServiceNameAzureRM: '<azure-service-connection>'
      commandOptions: '-auto-approve'
```

---

## Restore-from-scratch workflow
1. (Re)create the subscription if it was deleted.
2. Update `subscription_id` in `providers.tf` if it changed.
3. `terraform init`  → connects to remote state
4. `terraform plan`  → review what will be created
5. `terraform apply` → rebuilds the infrastructure
6. Restore data separately from Azure Backup.
'''
    with open(os.path.join(out_dir, "DEPLOY.md"), "w", encoding="utf-8") as f:
        f.write(content)


def export_scope(subscription_id, subscription_name, resource_group, out_root):
    """
    Export a single RG (if resource_group given) or every RG in the
    subscription (each into its own folder). Returns a summary dict.
    """
    os.makedirs(out_root, exist_ok=True)

    if resource_group:
        rgs = [resource_group]
    else:
        rgs = [rg["name"] for rg in list_resource_groups(subscription_id)]

    results, errors = [], []
    for rg in rgs:
        try:
            results.append(export_resource_group(
                subscription_id, subscription_name, rg, out_root))
        except Exception as e:
            errors.append({"resource_group": rg, "error": str(e)[:1200]})

    return {
        "subscription_id": subscription_id,
        "subscription_name": subscription_name,
        "scope": resource_group or "ALL resource groups",
        "exported": results,
        "errors": errors,
        "rg_count": len(rgs),
        "success_count": len(results),
    }
